library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

use work.memory_pkg.rom16x16_t;

entity rom16 is
    port (
        clk_i     : in std_logic;
        address_i : in std_logic_vector(15 downto 0);
        data_o    : out std_logic_vector(15 downto 0)
    );
end entity rom16;

architecture behavioral of rom16 is

    -- generated by coregen
    COMPONENT blk_mem_gen_0
      PORT (
        clka : IN STD_LOGIC;
        addra : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
        douta : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
      );
    END COMPONENT;

begin
    blk_mem0: blk_mem_gen_0
    port map (
        clka => clk_i,
        addra => address_i,
        douta => data_o
    );
end architecture;